//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication7
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate
    {
        public candidate()
        {
            this.results = new HashSet<result>();
        }
    
        public int Id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public byte[] image { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<result> results { get; set; }
    }
}
