//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication7
{
    using System;
    using System.Collections.Generic;
    
    public partial class election
    {
        public election()
        {
            this.results = new HashSet<result>();
        }
    
        public int Id { get; set; }
        public string office { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int resultId { get; set; }
    
        public virtual ICollection<result> results { get; set; }
    }
}
